spring:
  application:
    name: api-gateway
server:
  port: 8080
# Security Config
security:
  jwtKeyPrivate: "9c9c48d57077710e8a8ec4a72f0c959fa11ea2c2e1073b7c7d39b4eefff5ddf8"
  jwtUserGenerator: "AUTH0JWT-BACKEND"