server:
  port: 8081
spring:
  application:
    name: "ms-user"
  devtools:
    add-properties: false
  threads:
    virtual:
      enabled: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/ms-user"
    username: "admin"
    password: "admin"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: "none"
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
